[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "https://www.rosamruizpsicologa.es/*"
  to = "https://rosamruizpsicologa.es/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
